Repository privacy-ethereum/maci, pull requests merged in 2022-12, with the labels that each got.

#553 Fix/deployment error and bump version
  circuits/package-lock.json
  circuits/package.json
  cli/package-lock.json
  cli/package.json
  common/package.json
  contracts/package-lock.json
  contracts/package.json
  contracts/ts/deploy.ts
  core/package-lock.json
  core/package.json
  crypto/package-lock.json
  crypto/package.json
  domainobjs/package-lock.json
  domainobjs/package.json
  integrationTests/package-lock.json
  integrationTests/package.json
  lerna.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: bug, devops, 3

#562 Fix/server
  server/db.js
  server/handler_v0_10.js
  server/handler_v1.js
  server/utils.js
Labels: bug

#564 Update README.md of master branch to refer v1 branch
  README.md
Labels: documentation
