Repository privacy-ethereum/maci, pull requests merged in 2024-04, with the labels that each got.

#1336 chore: use non-zero start and end blocks for proof generation
  cli/ts/commands/genProofs.ts
  contracts/contracts/Poll.sol
  contracts/deploy-config-example.json
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/prove.ts
Labels: chore

#1343 feat(cli): add start block for signup event parsing
  cli/ts/commands/genLocalState.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/signup.ts
  cli/ts/utils/interfaces.ts
  contracts/tasks/helpers/ProofGenerator.ts
Labels: enhancement

#1349 feat(contracts): tally qv and non-qv optimisations
  cli/tests/ceremony-params/ceremonyParams.test.ts
  cli/tests/constants.ts
  cli/tests/e2e/e2e.nonQv.test.ts
  cli/tests/e2e/e2e.test.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/verify.ts
  cli/ts/index.ts
  cli/ts/utils/interfaces.ts
  cli/ts/utils/verifiers.ts
  contracts/contracts/MACI.sol
  contracts/contracts/Tally.sol
  contracts/contracts/TallyFactory.sol
  contracts/contracts/TallyNonQv.sol
  contracts/contracts/TallyNonQvFactory.sol
  contracts/contracts/interfaces/ITallyFactory.sol
  contracts/tasks/deploy/maci/08-tallyFactory.ts
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tasks/helpers/Prover.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/prove.ts
  contracts/tests/EASGatekeeper.test.ts
  contracts/tests/HatsGatekeeper.test.ts
  contracts/tests/MACI.test.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Poll.test.ts
  contracts/tests/SignUpGatekeeper.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/TallyNonQv.test.ts
  contracts/tests/utils.ts
  contracts/ts/deploy.ts
  contracts/ts/types.ts
  integrationTests/ts/__tests__/integration.test.ts
  integrationTests/ts/__tests__/maci-keys.test.ts
  website/versioned_docs/version-v1.x/cli.md
  website/versioned_docs/version-v1.x/poll-types.md
Labels: enhancement

#1364 chore: add qv and non-qv key setup during deploy
  cli/testScript.sh
  cli/tests/ceremony-params/ceremonyParams.test.ts
  cli/tests/constants.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/index.ts
  cli/ts/utils/interfaces.ts
  contracts/contracts/Tally.sol
  contracts/contracts/VkRegistry.sol
  contracts/deploy-config-example.json
  contracts/tasks/deploy/maci/10-vkRegistry.ts
  contracts/tests/VkRegistry.test.ts
  contracts/tests/constants.ts
  integrationTests/ts/__tests__/integration.test.ts
  website/versioned_docs/version-v1.3_alpha/cli.md
Labels: chore

#1369 feat: use mode instead of flag for voting option
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/proveOnChain.ts
  contracts/contracts/MACI.sol
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/MessageProcessorFactory.sol
  contracts/contracts/Tally.sol
  contracts/contracts/TallyFactory.sol
  contracts/contracts/VkRegistry.sol
  contracts/contracts/interfaces/IMPFactory.sol
  contracts/contracts/interfaces/ITallyFactory.sol
  contracts/contracts/interfaces/IVkRegistry.sol
  contracts/contracts/utilities/DomainObjs.sol
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tasks/helpers/Prover.ts
  contracts/tests/MACI.test.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Poll.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/TallyNonQv.test.ts
  integrationTests/ts/__tests__/maci-keys.test.ts
Labels: enhancement

#1372 chore(contracts): get rid of bash scripts for prebuild command
  contracts/package.json
  contracts/scripts/compileSol.sh
  contracts/scripts/compileSol.ts
  contracts/scripts/writeMerkleZeroesContracts.sh
  contracts/ts/buildPoseidon.ts
  contracts/ts/genZerosContract.ts
  contracts/tsconfig.build.json
  contracts/tsconfig.json
Labels: chore

#1380 fix(website): add typedoc folder to .gitignore and use pnpm v8 for ci
  .eslintrc.js
  .github/workflows/benchmarks.yml
  .github/workflows/checks.yml
  .github/workflows/circuit-build.yml
  .github/workflows/commitlint.yml
  .github/workflows/contracts-build.yml
  .github/workflows/core-build.yml
  .github/workflows/crypto-build.yml
  .github/workflows/domainobjs-build.yml
  .github/workflows/e2e.yml
  .github/workflows/nightly-ceremony.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-e2e.yml
  .github/workflows/slither.yml
  pnpm-lock.yaml
  website/.gitignore
  website/docusaurus.config.ts
  website/src/scripts/utils.ts
Labels: bug, chore

#1366 docs(add note about non qv on integrating): added a note about running non QV on Integrating page
  website/versioned_docs/version-v1.2/integrating.md
  website/versioned_docs/version-v1.3_alpha/integrating.md
Labels: documentation

#1378 docs: update integrating doc for v1.3
  website/versioned_docs/version-v1.2/integrating.md
  website/versioned_docs/version-v1.3_alpha/integrating.md
Labels: documentation

#1363 docs(website): update trouble shooting doc
  website/src/scripts/setupTypedoc.ts
  website/versioned_docs/version-v1.3_alpha/troubleshooting.md
Labels: documentation

#1386 feat(coordinator): add coordinator service boilerplate
  .github/workflows/coordinator-build.yml
  coordinator/.eslintrc.js
  coordinator/hardhat.config.ts
  coordinator/nest-cli.json
  coordinator/package.json
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/app.module.ts
  coordinator/ts/app.service.ts
  coordinator/ts/main.ts
  coordinator/tsconfig.build.json
  coordinator/tsconfig.json
  lerna.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#1392 feat: support deployment without hardhat
  cli/package.json
  cli/ts/commands/deploy.ts
  contracts/package.json
  contracts/tasks/deploy/maci/01-constantInitialVoiceCreditProxy.ts
  contracts/tasks/deploy/maci/02-gatekeepers.ts
  contracts/tasks/deploy/maci/03-verifier.ts
  contracts/tasks/deploy/maci/04-topupCredit.ts
  contracts/tasks/deploy/maci/05-poseidon.ts
  contracts/tasks/deploy/maci/06-pollFactory.ts
  contracts/tasks/deploy/maci/07-messageProcessorFactory.ts
  contracts/tasks/deploy/maci/08-tallyFactory.ts
  contracts/tasks/deploy/maci/09-maci.ts
  contracts/tasks/deploy/maci/10-vkRegistry.ts
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/Deployment.ts
  contracts/tasks/helpers/abi.ts
  contracts/tasks/helpers/types.ts
  contracts/tests/AccQueue.test.ts
  contracts/tests/AccQueueBenchmark.test.ts
  contracts/tests/Hasher.test.ts
  contracts/tests/HasherBenchmarks.test.ts
  contracts/tests/Utilities.test.ts
  contracts/tests/utils.ts
  contracts/ts/deploy.ts
  contracts/ts/index.ts
  coordinator/.env.example
  coordinator/package.json
  coordinator/ts/app.module.ts
  coordinator/ts/main.ts
  integrationTests/package.json
  pnpm-lock.yaml
Labels: enhancement

#1407 feat(cli): add export from contracts, circuits for cli package
  cli/ts/sdk/index.ts
Labels: enhancement
