Repository privacy-ethereum/maci, pull requests merged in 2024-01, with the labels that each got.

#924 test(core): process messages unit tests
  core/ts/Poll.ts
  core/ts/__tests__/MaciState.test.ts
Labels: testing

#933 test(crypto): complete unit tests for the crypto package
  crypto/package.json
  crypto/ts/__tests__/Crypto.test.ts
  crypto/ts/crypto.ts
  crypto/ts/index.ts
  crypto/ts/utils.ts
Labels: testing

#945 chore(circuits): integrate linter
  circuits/.eslintrc.js
  circuits/package.json
  circuits/ts/__tests__/CalculateTotal.test.ts
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/Ecdh.test.ts
  circuits/ts/__tests__/Hasher.test.ts
  circuits/ts/__tests__/MessageToCommand.test.ts
  circuits/ts/__tests__/MessageValidator.test.ts
  circuits/ts/__tests__/PrivToPubKey.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  circuits/ts/__tests__/Splicer.test.ts
  circuits/ts/__tests__/StateLeafAndBallotTransformer.test.ts
  circuits/ts/__tests__/TallyVotes.test.ts
  circuits/ts/__tests__/UnpackElement.test.ts
  circuits/ts/__tests__/VerifySignature.test.ts
  circuits/ts/__tests__/utils/utils.ts
  circuits/ts/proofs.ts
  circuits/ts/types.ts
  circuits/ts/types/circom_tester.d.ts
  circuits/ts/types/snarkjs.d.ts
  circuits/ts/utils.ts
  circuits/tsconfig.json
Labels: chore

#946 chore(core): integrate linter
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  core/.eslintrc.js
  core/package-lock.json
  core/package.json
  core/ts/MaciState.ts
  core/ts/Poll.ts
  core/ts/__tests__/MaciState.test.ts
  core/ts/__tests__/ProcessMessage.test.ts
  core/ts/index.ts
  core/ts/utils/types.ts
  core/ts/utils/utils.ts
  core/tsconfig.json
  crypto/ts/index.ts
Labels: chore

#944 refactor(crypto): remove ffjavascript and implement utils functions locally
  .github/scripts/ceremony-param-tests-c-witness.sh
  circuits/ts/__tests__/MessageValidator.test.ts
  circuits/ts/__tests__/Splicer.test.ts
  circuits/ts/__tests__/StateLeafAndBallotTransformer.test.ts
  cli/tests/constants.ts
  core/ts/Poll.ts
  crypto/package-lock.json
  crypto/package.json
  crypto/ts/@types/ffjavascript.d.ts
  crypto/ts/@types/main.d.ts
  crypto/ts/AccQueue.ts
  crypto/ts/__tests__/Crypto.test.ts
  crypto/ts/__tests__/Utils.test.ts
  crypto/ts/bigIntUtils.ts
  crypto/ts/crypto.ts
  crypto/ts/index.ts
  crypto/ts/types.ts
  crypto/ts/utils.ts
  domainobjs/ts/__tests__/privateKey.test.ts
Labels: dependencies

#948 fix(signups): ensure we account for the blank state leaf
  cli/ts/commands/proveOnChain.ts
  contracts/contracts/MACI.sol
  contracts/contracts/Subsidy.sol
  contracts/tests/MACI.test.ts
  core/ts/MaciState.ts
Labels: bug, smart contracts

#943 refactor(zk-kit-poseidon): remove old circomlib dependencies in crypto
  .github/scripts/ceremony-param-tests-c-witness.sh
  contracts/package-lock.json
  contracts/package.json
  contracts/ts/genMaciState.ts
  core/package-lock.json
  crypto/package-lock.json
  crypto/package.json
  crypto/ts/@types/blake-hash.d.ts
  crypto/ts/@types/circomlib.d.ts
  crypto/ts/@types/main.d.ts
  crypto/ts/__tests__/Crypto.test.ts
  crypto/ts/__tests__/Utils.test.ts
  crypto/ts/bigIntUtils.ts
  crypto/ts/constants.ts
  crypto/ts/crypto.ts
  crypto/ts/index.ts
  crypto/ts/types.ts
  domainobjs/ts/__tests__/publicKey.test.ts
  domainobjs/ts/commands/PCommand.ts
  domainobjs/ts/privateKey.ts
  domainobjs/ts/publicKey.ts
  integrationTests/package-lock.json
  integrationTests/package.json
  integrationTests/ts/__tests__/maci-keys.test.ts
  integrationTests/ts/__tests__/utils/utils.ts
Labels: dependencies

#934 test(domainobjs): implement unit tests for the domainobjs package
  .github/scripts/ceremony-param-tests-c-witness.sh
  domainobjs/package.json
  domainobjs/ts/__tests__/ballot.test.ts
  domainobjs/ts/__tests__/commands.test.ts
  domainobjs/ts/__tests__/keypair.test.ts
  domainobjs/ts/__tests__/message.test.ts
  domainobjs/ts/__tests__/privateKey.test.ts
  domainobjs/ts/__tests__/publicKey.test.ts
  domainobjs/ts/__tests__/stateLeaf.test.ts
  domainobjs/ts/__tests__/verifyingKey.test.ts
  domainobjs/ts/privateKey.ts
Labels: testing

#919 refactor(contracts): smart contracts optimizations
  contracts/contracts/MACI.sol
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/Poll.sol
  contracts/contracts/PollFactory.sol
  contracts/contracts/SignUpToken.sol
  contracts/contracts/Subsidy.sol
  contracts/contracts/Tally.sol
  contracts/contracts/TopupCredit.sol
  contracts/contracts/VkRegistry.sol
  contracts/contracts/gatekeepers/FreeForAllSignUpGatekeeper.sol
  contracts/contracts/gatekeepers/SignUpTokenGatekeeper.sol
  contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol
  contracts/contracts/trees/AccQueue.sol
  contracts/contracts/utilities/Utilities.sol
  contracts/tests/Subsidy.test.ts
  contracts/tests/Tally.test.ts
Labels: smart contracts

#950 chore(cli): integrate linter
  .github/workflows/reusable-e2e.yml
  cli/.eslintrc.js
  cli/hardhat.config.ts
  cli/package-lock.json
  cli/package.json
  cli/tests/constants.ts
  cli/tests/e2e.subsidy.test.ts
  cli/tests/e2e.test.ts
  cli/tests/keyChange.test.ts
  cli/tests/utils.ts
  cli/ts/commands/airdrop.ts
  cli/ts/commands/checkVerifyingKeys.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/deployVkRegistry.ts
  cli/ts/commands/fundWallet.ts
  cli/ts/commands/genKeyPair.ts
  cli/ts/commands/genLocalState.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/genPubKey.ts
  cli/ts/commands/mergeMessages.ts
  cli/ts/commands/mergeSignups.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/commands/publish.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/commands/showContracts.ts
  cli/ts/commands/signup.ts
  cli/ts/commands/timeTravel.ts
  cli/ts/commands/topup.ts
  cli/ts/commands/verify.ts
  cli/ts/index.ts
  cli/ts/utils/banner.ts
  cli/ts/utils/constants.ts
  cli/ts/utils/contracts.ts
  cli/ts/utils/formatting.ts
  cli/ts/utils/index.ts
  cli/ts/utils/interfaces.ts
  cli/ts/utils/prompts.ts
  cli/ts/utils/salt.ts
  cli/ts/utils/storage.ts
  cli/ts/utils/theme.ts
  cli/ts/utils/time.ts
  cli/ts/utils/trees.ts
  cli/ts/utils/verifiers.ts
  cli/ts/utils/vks.ts
  cli/tsconfig.json
  contracts/hardhat.config.ts
  contracts/package-lock.json
  contracts/package.json
  contracts/tests/HasherBenchmarks.test.ts
  contracts/ts/index.ts
  contracts/ts/utils.ts
  core/ts/__tests__/MaciState.test.ts
  core/ts/index.ts
  integrationTests/hardhat.config.ts
  integrationTests/package.json
  integrationTests/ts/__tests__/integration.test.ts
Labels: chore

#951 chore(contracts): enable linter
  .github/workflows/checks.yml
  .lintstagedrc.json
  .solhint.json
  cli/ts/commands/proveOnChain.ts
  contracts/contracts/MACI.sol
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/Poll.sol
  contracts/contracts/PollFactory.sol
  contracts/contracts/SignUpToken.sol
  contracts/contracts/Subsidy.sol
  contracts/contracts/Tally.sol
  contracts/contracts/TopupCredit.sol
  contracts/contracts/benchmarks/HasherBenchmarks.sol
  contracts/contracts/crypto/Hasher.sol
  contracts/contracts/crypto/IVerifier.sol
  contracts/contracts/crypto/MockVerifier.sol
  contracts/contracts/crypto/Pairing.sol
  contracts/contracts/crypto/PoseidonT3.sol
  contracts/contracts/crypto/PoseidonT4.sol
  contracts/contracts/crypto/PoseidonT5.sol
  contracts/contracts/crypto/PoseidonT6.sol
  contracts/contracts/crypto/Verifier.sol
  contracts/contracts/gatekeepers/FreeForAllSignUpGatekeeper.sol
  contracts/contracts/gatekeepers/SignUpGatekeeper.sol
  contracts/contracts/gatekeepers/SignUpTokenGatekeeper.sol
  contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol
  contracts/contracts/initialVoiceCreditProxy/InitialVoiceCreditProxy.sol
  contracts/contracts/interfaces/IMACI.sol
  contracts/contracts/trees/AccQueue.sol
  contracts/contracts/trees/AccQueueBinary.sol
  contracts/contracts/trees/AccQueueBinary0.sol
  contracts/contracts/trees/AccQueueBinaryMaci.sol
  contracts/contracts/trees/AccQueueQuinary.sol
  contracts/contracts/trees/AccQueueQuinary0.sol
  contracts/contracts/trees/AccQueueQuinaryBlankSl.sol
  contracts/contracts/trees/AccQueueQuinaryMaci.sol
  contracts/contracts/utilities/CommonUtilities.sol
  contracts/contracts/utilities/DomainObjs.sol
  contracts/contracts/utilities/Params.sol
  contracts/contracts/utilities/Utilities.sol
  contracts/ts/abi.ts
  package.json
Labels: chore

#956 test(cli): reorganize e2e tests and add more tests for cli commands
  cli/package.json
  cli/tests/e2e.test.ts
  cli/tests/e2e/e2e.subsidy.test.ts
  cli/tests/e2e/e2e.test.ts
  cli/tests/e2e/keyChange.test.ts
  cli/tests/unit/airdrop.test.ts
  cli/tests/unit/data/testVk.json
  cli/tests/unit/fundWallet.test.ts
  cli/tests/unit/genKeyPair.test.ts
  cli/tests/unit/genPubkey.test.ts
  cli/tests/unit/timeTravel.test.ts
  cli/tests/unit/topup.test.ts
  cli/tests/unit/utils.test.ts
  contracts/hardhat.config.ts
  integrationTests/package.json
Labels: testing

#957 test(integration): ensure integration tests are using the correct user keys
  integrationTests/ts/__tests__/integration.test.ts
Labels: testing

#958 chore: linter unification
  .eslintrc.js
  circuits/.eslintrc.js
  circuits/tsconfig.json
  cli/.eslintrc.js
  cli/tsconfig.json
  contracts/.eslintrc.js
  contracts/tsconfig.json
  core/.eslintrc.js
  core/tsconfig.json
  crypto/.eslintrc.js
  crypto/tsconfig.json
  domainobjs/.eslintrc.js
  domainobjs/tsconfig.json
  integrationTests/.eslintrc.js
  integrationTests/tsconfig.json
  tsconfig.json
Labels: chore

#959 chore: add types check
  .github/workflows/checks.yml
  .husky/pre-commit
  circuits/package.json
  cli/package.json
  contracts/package.json
  core/package.json
  crypto/package.json
  domainobjs/package.json
  integrationTests/package.json
  package.json
  website/package-lock.json
  website/package.json
Labels: chore

#960 docs(testing): revisit testing docs and add more detailed info
  integrationTests/ts/__tests__/data/suites.json
  integrationTests/ts/__tests__/utils/interfaces.ts
  integrationTests/ts/__tests__/utils/utils.ts
  website/versioned_docs/version-v1.x/audit.md
  website/versioned_docs/version-v1.x/ci-pipeline.md
  website/versioned_docs/version-v1.x/coordinator-processing.md
  website/versioned_docs/version-v1.x/integrating.md
  website/versioned_docs/version-v1.x/key-change.md
  website/versioned_docs/version-v1.x/spec.md
  website/versioned_docs/version-v1.x/testing-in-details.md
  website/versioned_docs/version-v1.x/testing.md
  website/versioned_docs/version-v1.x/troubleshooting.md
  website/versioned_docs/version-v1.x/versioning.md
Labels: documentation

#961 chore: bundle size optimizations
  circuits/ts/proofs.ts
  cli/package-lock.json
  cli/package.json
  cli/ts/commands/airdrop.ts
  cli/ts/commands/checkVerifyingKeys.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/mergeMessages.ts
  cli/ts/commands/mergeSignups.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/commands/publish.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/commands/signup.ts
  cli/ts/commands/topup.ts
  cli/ts/commands/verify.ts
  contracts/contracts/MACI.sol
  contracts/contracts/PollFactory.sol
  contracts/contracts/VkRegistry.sol
  contracts/contracts/gatekeepers/FreeForAllSignUpGatekeeper.sol
  contracts/package-lock.json
  contracts/package.json
  contracts/ts/abi.ts
  contracts/ts/deploy.ts
  contracts/ts/deployer.ts
  contracts/ts/genMaciState.ts
  contracts/ts/index.ts
  contracts/ts/types.ts
  contracts/ts/utils.ts
  core/ts/MaciState.ts
  core/ts/Poll.ts
  crypto/package-lock.json
  crypto/package.json
  crypto/ts/babyjub.ts
  crypto/ts/bigIntUtils.ts
  crypto/ts/constants.ts
  crypto/ts/hashing.ts
  crypto/ts/types.ts
  domainobjs/package-lock.json
  domainobjs/package.json
  domainobjs/ts/commands/PCommand.ts
  domainobjs/ts/message.ts
  domainobjs/ts/privateKey.ts
  domainobjs/ts/publicKey.ts
  integrationTests/package-lock.json
  integrationTests/package.json
Labels: dependencies, chore

#965 chore: add dependabot and codeowners
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: dependencies, chore

#972 chore: ignore dependabot commit messages for linting
  commitlint.config.js
Labels: chore

#963 chore(deps): update project dependencies and remove redundant ones
  circuits/package-lock.json
  circuits/package.json
  cli/package-lock.json
  cli/package.json
  cli/ts/commands/genProofs.ts
  cli/ts/utils/interfaces.ts
  contracts/package-lock.json
  contracts/package.json
  core/package-lock.json
  crypto/package-lock.json
  domainobjs/package-lock.json
  integrationTests/package-lock.json
  integrationTests/package.json
  package-lock.json
  package.json
  website/package-lock.json
Labels: dependencies

#974 chore(cli): optimize bundle size
  circuits/package.json
  circuits/tsconfig.build.json
  cli/package.json
  cli/tsconfig.build.json
  contracts/package.json
  contracts/tsconfig.build.json
  core/package.json
  core/tsconfig.build.json
  crypto/package.json
  crypto/tsconfig.build.json
  domainobjs/package.json
  domainobjs/tsconfig.build.json
Labels: chore

#993 fixed header in release post
  website/blog/2021-10-12-maci-v1.md
Labels: documentation

#1007 chore: enable codeql and workflows cleanup
  .github/CODEOWNERS
  .github/workflows/codeql.yml
  .github/workflows/contracts-build.yml
  .github/workflows/core-build.yml
  .github/workflows/crypto-build.yml
  .github/workflows/domainobjs-build.yml
  .prettierignore
  website/versioned_docs/version-v1.x/versioning.md
Labels: devops, Security, chore

#1008 refactor(contracts): optimize code
  .github/scripts/ceremony-param-tests-c-witness.sh
  contracts/contracts/MACI.sol
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/Poll.sol
  contracts/contracts/Subsidy.sol
  contracts/contracts/Tally.sol
  website/versioned_docs/version-v1.x/contracts.md
Labels: smart contracts

#1018 feat(circuits): unify circuits compilation and zkey generation processes
  .github/scripts/ceremony-param-tests-c-witness.sh
  .github/workflows/nightly.yml
  .github/workflows/reusable-e2e.yml
  circuits/.gitignore
  circuits/circom/circuits.json
  circuits/package.json
  circuits/scripts/buildCustomSnarks.sh
  circuits/scripts/build_arm.sh
  circuits/scripts/build_intel.sh
  circuits/ts/compile.ts
  circuits/ts/genZkeys.ts
  circuits/ts/types.ts
  cli/package.json
  cli/tests/constants.ts
  cli/tests/e2e/e2e.subsidy.test.ts
  cli/tests/e2e/e2e.test.ts
  cli/tests/e2e/keyChange.test.ts
  cli/ts/commands/genProofs.ts
  cli/ts/index.ts
  cli/zkeys.config.yml
  crypto/package.json
  integrationTests/scripts/download_zkeys.sh
  integrationTests/ts/__tests__/integration.test.ts
  package.json
  pnpm-lock.yaml
  website/versioned_docs/version-v1.x/circuits.md
  website/versioned_docs/version-v1.x/cli.md
  website/versioned_docs/version-v1.x/installation.md
  website/versioned_docs/version-v1.x/testing.md
  website/versioned_docs/version-v1.x/troubleshooting.md
Labels: documentation, dependencies, devops, testing, circuits

#1025 fix(cli): remove files property from package.json
  .github/workflows/codeql.yml
  .prettierignore
  cli/package.json
  crypto/package.json
  pnpm-lock.yaml
Labels: bug

#1027 fix(cli): add env initialization for hardhat conifg
  cli/ts/cliInit.ts
  cli/ts/index.ts
Labels: bug

#1028 chore(cli): change maci-cli script run instructions
  .github/scripts/ceremony-param-tests-c-witness.sh
  cli/testScript.sh
  website/versioned_docs/version-v1.x/cli.md
  website/versioned_docs/version-v1.x/troubleshooting.md
Labels: chore

#1029 fix(circuits): replace execSync with execFileSync
  circuits/ts/compile.ts
  circuits/ts/proofs.ts
Labels: Security

#964 feat: add new post on roadmap updates
  website/blog/2024-01-18-roadmap.md
  website/blog/index.md
Labels: documentation

#1061 docs(integration): clarify integraration docs
  website/versioned_docs/version-v1.x/integrating.md
Labels: documentation

#1083 feat: optimize deployment and tally event
  .solhint.json
  cli/tests/unit/topup.test.ts
  cli/ts/commands/airdrop.ts
  cli/ts/commands/checkVerifyingKeys.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/deployVkRegistry.ts
  cli/ts/commands/genLocalState.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/mergeMessages.ts
  cli/ts/commands/mergeSignups.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/commands/publish.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/commands/signup.ts
  cli/ts/commands/topup.ts
  cli/ts/commands/verify.ts
  cli/ts/index.ts
  cli/ts/utils/interfaces.ts
  cli/ts/utils/storage.ts
  contracts/contracts/MACI.sol
  contracts/contracts/Tally.sol
  contracts/contracts/trees/AccQueue.sol
  contracts/contracts/trees/AccQueueBinary.sol
  contracts/contracts/trees/AccQueueQuinary.sol
  contracts/tests/AccQueueBenchmark.test.ts
  contracts/tests/Hasher.test.ts
  contracts/tests/HasherBenchmarks.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/Utilities.test.ts
  contracts/tests/utils.ts
  contracts/ts/deploy.ts
  contracts/ts/index.ts
  contracts/ts/types.ts
  contracts/ts/utils.ts
  integrationTests/ts/__tests__/utils/utils.ts
  package.json
  website/versioned_docs/version-v1.x/cli.md
  website/versioned_docs/version-v1.x/integrating.md
Labels: documentation, enhancement, chore

#1095 chore: add slither github action
  .github/workflows/slither.yml
Labels: Security, chore

#1093 fix(crypto): get rid of potential prototype polution
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  circuits/ts/__tests__/TallyVotes.test.ts
  contracts/tests/AccQueue.test.ts
  contracts/tests/AccQueueBenchmark.test.ts
  contracts/tests/utils.ts
  crypto/ts/AccQueue.ts
  crypto/ts/__tests__/utils.ts
  crypto/ts/types.ts
Labels: Security

#1089 refactor(contracts): remove maxValues from Maci.deployPoll() and instead calculate
  cli/tests/constants.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/index.ts
  cli/ts/utils/interfaces.ts
  contracts/contracts/MACI.sol
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/Poll.sol
  contracts/contracts/PollFactory.sol
  contracts/contracts/Subsidy.sol
  contracts/contracts/Tally.sol
  contracts/contracts/interfaces/IPoll.sol
  contracts/contracts/interfaces/IPollFactory.sol
  contracts/contracts/utilities/Params.sol
  contracts/tests/MACI.test.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Poll.test.ts
  contracts/tests/PollFactory.test.ts
  contracts/tests/Subsidy.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/constants.ts
  contracts/ts/genMaciState.ts
  integrationTests/ts/__tests__/integration.test.ts
  integrationTests/ts/__tests__/maci-keys.test.ts
Labels: smart contracts

#1106 chore(contract): add deploy tasks for maci
  .prettierignore
  contracts/.env.example
  contracts/.gitignore
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/tasks/deploy/index.ts
  contracts/tasks/deploy/maci/01-constantInitialVoiceCreditProxy.ts
  contracts/tasks/deploy/maci/02-freeForAllSignUpGatekeeper.ts
  contracts/tasks/deploy/maci/03-verifier.ts
  contracts/tasks/deploy/maci/04-topupCredit.ts
  contracts/tasks/deploy/maci/05-poseidon.ts
  contracts/tasks/deploy/maci/06-pollFactory.ts
  contracts/tasks/deploy/maci/07-messageProcessorFactory.ts
  contracts/tasks/deploy/maci/08-tallyFactory.ts
  contracts/tasks/deploy/maci/09-subsidyFactory.ts
  contracts/tasks/deploy/maci/10-maci.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/Deployment.ts
  contracts/tasks/helpers/constants.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/deployFull.ts
  contracts/ts/deploy.ts
  contracts/ts/utils.ts
  contracts/tsconfig.build.json
  contracts/tsconfig.json
  integrationTests/hardhat.config.ts
  pnpm-lock.yaml
Labels: chore

#1122 chore(contract): add contract verification task
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/tasks/deploy/maci/05-poseidon.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/ContractVerifier.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/deployFull.ts
  contracts/tasks/runner/verifyFull.ts
Labels: chore

#1132 docs(contracts): add documentation for deployment workflow
  contracts/hardhat.config.ts
  contracts/tasks/deploy/index.ts
  contracts/tasks/deploy/maci/01-constantInitialVoiceCreditProxy.ts
  contracts/tasks/deploy/maci/02-freeForAllSignUpGatekeeper.ts
  contracts/tasks/deploy/maci/03-verifier.ts
  contracts/tasks/deploy/maci/04-topupCredit.ts
  contracts/tasks/deploy/maci/05-poseidon.ts
  contracts/tasks/deploy/maci/06-pollFactory.ts
  contracts/tasks/deploy/maci/07-messageProcessorFactory.ts
  contracts/tasks/deploy/maci/08-tallyFactory.ts
  contracts/tasks/deploy/maci/09-subsidyFactory.ts
  contracts/tasks/deploy/maci/10-maci.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/ContractVerifier.ts
  contracts/tasks/helpers/Deployment.ts
  contracts/tasks/helpers/constants.ts
  contracts/tasks/runner/deployFull.ts
  contracts/tasks/runner/verifyFull.ts
Labels: documentation

#1142 chore(contract): add deploy script for eas gatekeeper
  .prettierignore
  contracts/.gitignore
  contracts/deploy-config-example.json
  contracts/hardhat.config.ts
  contracts/tasks/deploy/maci/01-constantInitialVoiceCreditProxy.ts
  contracts/tasks/deploy/maci/02-freeForAllSignUpGatekeeper.ts
  contracts/tasks/deploy/maci/02-gatekeepers.ts
  contracts/tasks/deploy/maci/10-maci.ts
  contracts/tasks/helpers/Deployment.ts
  contracts/tasks/helpers/constants.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/deployFull.ts
Labels: chore
