Repository privacy-ethereum/maci, pull requests merged in 2024-06, with the labels that each got.

#1530 fix(circuits): remove only for circuits tests
  circuits/ts/__tests__/IncrementalQuinaryTree.test.ts
Labels: bug

#1545 fix(subgraph): add version and files for package.json
  subgraph/package.json
Labels: bug

#1553 fix(subgraph): remove user-polls relation
  subgraph/schemas/schema.v1.graphql
  subgraph/src/maci.ts
Labels: bug

#1556 feat(subgraph): optimize subgraph schema
  subgraph/.gitignore
  subgraph/config/optimism-sepolia.json
  subgraph/schemas/schema.v1.graphql
  subgraph/src/maci.ts
  subgraph/src/poll.ts
  subgraph/src/utils/entity.ts
Labels: enhancement

#1564 feat(subgraph): optimize subgraph schema (maci)
  subgraph/schemas/schema.v1.graphql
  subgraph/src/maci.ts
  subgraph/src/poll.ts
  subgraph/src/utils/constants.ts
  subgraph/src/utils/entity.ts
  subgraph/tests/maci/maci.test.ts
  subgraph/tests/poll/poll.test.ts
Labels: enhancement

#1571 docs: ensure that it's clear that num signups account for empty leaf
  website/versioned_docs/version-v1.2/contracts.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Poll.md
Labels: documentation

#1570 docs(use-cases): add use cases entry in the doc website and start adding content
  website/versioned_docs/version-v2.0_alpha/contributing/_category_.json
  website/versioned_docs/version-v2.0_alpha/processes/_category_.json
  website/versioned_docs/version-v2.0_alpha/project-ideas/_category_.json
  website/versioned_docs/version-v2.0_alpha/security/_category_.json
  website/versioned_docs/version-v2.0_alpha/testing/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/governance/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/governance/governance.md
  website/versioned_docs/version-v2.0_alpha/use-cases/local-elections/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/local-elections/local-elections.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/public-goods.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/apply.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/case-studies.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/faq.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/how-it-works.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/registration-approaches.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/what-is-quadratic-funding.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/_category_.json
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/case-studies.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/how-it-works.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/registration-approaches.md
  website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/what-is-retroactive-public-goods-funding.md
Labels: documentation

#1586 docs: add documentation entry for already deployed smart contracts
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/DeployedContracts.md
Labels: documentation

#1610 docs: update contributing guide with squash info
  website/versioned_docs/version-v1.2/contributing/contributing.md
  website/versioned_docs/version-v2.0_alpha/contributing/contributing.md
Labels: documentation
