Repository privacy-ethereum/maci, pull requests merged in 2024-05, with the labels that each got.

#1416 feat(contracts): add new adapter for lowdb to support browser env
  cli/ts/sdk/index.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/Deployment.ts
  contracts/tsconfig.build.json
  contracts/tsconfig.json
Labels: enhancement

#1417 feat(multiple-polls): allow concurrent polls
  .github/workflows/reusable-e2e.yml
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/non-qv/tallyVotes.circom
  circuits/circom/core/qv/processMessages.circom
  circuits/circom/core/qv/tallyVotes.circom
  circuits/circom/trees/incrementalMerkleTree.circom
  circuits/circom/utils/processMessagesInputHasher.circom
  circuits/circom/utils/processTopup.circom
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  circuits/ts/__tests__/TallyVotes.test.ts
  circuits/ts/__tests__/utils/constants.ts
  circuits/ts/types.ts
  cli/tests/e2e/e2e.test.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/genLocalState.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/mergeSignups.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/utils/interfaces.ts
  contracts/contracts/MACI.sol
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/Poll.sol
  contracts/contracts/Tally.sol
  contracts/contracts/interfaces/IMACI.sol
  contracts/contracts/interfaces/IPoll.sol
  contracts/contracts/trees/EmptyBallotRoots.sol
  contracts/contracts/trees/LazyIMT.sol
  contracts/contracts/trees/zeros/MerkleBinaryBlankSl.sol
  contracts/package.json
  contracts/scripts/compileSol.ts
  contracts/tasks/deploy/maci/09-maci.ts
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/helpers/TreeMerger.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/merge.ts
  contracts/tests/MACI.test.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Poll.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/TallyNonQv.test.ts
  contracts/tests/constants.ts
  contracts/tests/utils.ts
  contracts/ts/deploy.ts
  contracts/ts/genEmptyBallotRootsContract.ts
  contracts/ts/genMaciState.ts
  contracts/ts/types.ts
  core/ts/Poll.ts
  core/ts/__tests__/Poll.test.ts
  core/ts/__tests__/e2e.test.ts
  core/ts/index.ts
  core/ts/utils/constants.ts
  core/ts/utils/types.ts
  crypto/ts/quinTree.ts
  package.json
  pnpm-lock.yaml
  website/versioned_docs/version-v1.2/solidity-docs/interfaces/IMACI.md
  website/versioned_docs/version-v1.3_alpha/spec.md
Labels: enhancement

#1424 feat(coordinator): add crypto and proof generation services
  .github/workflows/coordinator-build.yml
  contracts/ts/index.ts
  coordinator/.env.example
  coordinator/.gitignore
  coordinator/package.json
  coordinator/scripts/generateKeypair.ts
  coordinator/ts/crypto/__tests__/crypto.service.test.ts
  coordinator/ts/crypto/crypto.service.ts
  coordinator/ts/main.ts
  coordinator/ts/proof/__tests__/proof.service.test.ts
  coordinator/ts/proof/proof.service.ts
  coordinator/ts/proof/types.ts
  coordinator/tsconfig.build.json
  coordinator/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#1433 feat(coordinator): add coordinator controller
  .github/workflows/coordinator-build.yml
  .github/workflows/nightly.yml
  .github/workflows/reusable-e2e.yml
  contracts/scripts/compileSol.ts
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/runner/prove.ts
  coordinator/.env.example
  coordinator/.gitignore
  coordinator/hardhat.config.ts
  coordinator/package.json
  coordinator/scripts/downloadZkeys.ts
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/app.module.ts
  coordinator/ts/app.service.ts
  coordinator/ts/jest/transform.js
  coordinator/ts/proof/__tests__/proof.service.test.ts
  coordinator/ts/proof/proof.service.ts
  coordinator/ts/proof/types.ts
  package.json
  pnpm-lock.yaml
  website/versioned_docs/version-v1.3_alpha/circuits.md
  website/versioned_docs/version-v1.3_alpha/installation.md
  website/versioned_docs/version-v1.3_alpha/testing.md
  website/versioned_docs/version-v1.3_alpha/troubleshooting.md
Labels: enhancement

#1442 chore(release): publish 1.2.1
  CHANGELOG.md
  circuits/CHANGELOG.md
  circuits/package.json
  cli/CHANGELOG.md
  cli/package.json
  contracts/CHANGELOG.md
  contracts/package.json
  coordinator/package.json
  core/CHANGELOG.md
  core/package.json
  crypto/CHANGELOG.md
  crypto/package.json
  domainobjs/CHANGELOG.md
  domainobjs/package.json
  integrationTests/CHANGELOG.md
  integrationTests/package.json
  lerna.json
  pnpm-lock.yaml
  website/CHANGELOG.md
  website/package.json
Labels: chore

#1451 feat(coordinator): auth-z and validation
  .github/workflows/coordinator-build.yml
  coordinator/.env.example
  coordinator/hardhat.config.ts
  coordinator/package.json
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/auth/AccountSignatureGuard.service.ts
  coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
  coordinator/ts/main.ts
  coordinator/ts/proof/__tests__/proof.service.test.ts
  coordinator/ts/proof/dto.ts
  coordinator/ts/proof/proof.service.ts
  coordinator/ts/proof/types.ts
  pnpm-lock.yaml
Labels: enhancement

#1441 docs(post-mortem): upload post mortem writeup
  website/blog/2024-05-08-ethdam.md
Labels: documentation

#1459 feat(coordinator): add generic errors
  coordinator/.env.example
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/common/errors.ts
  coordinator/ts/common/index.ts
  coordinator/ts/crypto/__tests__/crypto.service.test.ts
  coordinator/ts/crypto/crypto.service.ts
  coordinator/ts/main.ts
  coordinator/ts/proof/__tests__/proof.service.test.ts
  coordinator/ts/proof/proof.service.ts
Labels: enhancement

#1463 fix(nightly): do not run maci-coordinator tests from root on nightly
  package.json
Labels: ci-bug

#1466 fix(contract): gatekeeper deploy config skip
  contracts/package.json
  contracts/tasks/deploy/maci/02-gatekeepers.ts
  pnpm-lock.yaml
Labels: bug

#1467 docs(coordinator): add readme docs for coordinator
  coordinator/.env.example
  coordinator/README.md
  coordinator/hardhat.config.ts
  coordinator/package.json
Labels: documentation

#1469 docs(coordinator): add swagger support
  coordinator/hardhat.config.js
  coordinator/package.json
  coordinator/ts/app.controller.ts
  coordinator/ts/jest/setup.ts
  coordinator/ts/main.ts
  coordinator/ts/proof/dto.ts
  coordinator/tsconfig.build.json
  coordinator/tsconfig.json
  pnpm-lock.yaml
Labels: documentation

#1461 ci: add typo detection tool
  .github/workflows/config/typos.toml
  .github/workflows/typos.yml
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/qv/processMessages.circom
  circuits/circom/utils/non-qv/stateLeafAndBallotTransformer.circom
  circuits/circom/utils/qv/stateLeafAndBallotTransformer.circom
  cli/ts/commands/genProofs.ts
  contracts/tasks/runner/prove.ts
  contracts/tests/utils.ts
  contracts/ts/types.ts
  domainobjs/ts/commands/PCommand.ts
  integrationTests/ts/__tests__/utils/utils.ts
  website/versioned_docs/version-v1.2/typedoc/domainobjs/classes/PCommand.md
Labels: devops

#1473 fix: typos workflow
  .github/workflows/config/typos.toml
  .github/workflows/typos.yml
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/qv/processMessages.circom
  website/blog/2023-01-18-maci-v1.1.1.md
  website/blog/2024-04-10-roadmap-q2.md
  website/versioned_docs/version-v0.x/state-root-transition-circuit.md
Labels: documentation, devops

#1468 feat: add extract vk command in maci-cli
  cli/ts/commands/extractVkToFile.ts
  cli/ts/commands/index.ts
  cli/ts/index.ts
  cli/ts/utils/index.ts
  cli/ts/utils/interfaces.ts
  website/versioned_docs/version-v1.3_alpha/cli.md
Labels: chore

#1474 chore(coordinator): add logger
  coordinator/package.json
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/auth/AccountSignatureGuard.service.ts
  coordinator/ts/crypto/crypto.service.ts
  coordinator/ts/main.ts
  coordinator/ts/proof/proof.service.ts
Labels: chore

#1477 fix(poll-command): fixed poll command to support merged state root
  cli/tests/unit/poll.test.ts
  cli/ts/commands/poll.ts
  cli/ts/utils/interfaces.ts
Labels: bug

#1472 docs: smart contracts
  website/versioned_docs/version-v2.0_alpha/developers-references/integrating.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/AccQueue.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Gatekeepers.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MessageProcessor.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Params.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Poll.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/PollFactory.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Tally.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/VkRegistry.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/VoiceCreditProxy.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/_category_.json
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/contracts.md
  website/versioned_docs/version-v2.0_alpha/overview/overview.md
  website/versioned_docs/version-v2.0_alpha/quick-start/troubleshooting.md
  website/versioned_docs/version-v2.0_alpha/quick-start/workflow.md
Labels: documentation

#1478 docs(solidity-docs): add index page inside folders
  website/src/scripts/setupSolidityDocs.ts
  website/src/scripts/setupTypedoc.ts
  website/src/scripts/utils.ts
  website/versioned_docs/version-v2.0_alpha/contributing/_category_.json
  website/versioned_docs/version-v2.0_alpha/processes/_category_.json
  website/versioned_docs/version-v2.0_alpha/project-ideas/_category_.json
Labels: documentation

#1486 docs: split primitives into own files and update to latest changes
  website/versioned_docs/version-v1.2/circuits.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/ballot.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/coordinator-processing.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/hashing-and-encryption.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/key-change.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/maci-keys.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/maci-messages.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/merkle-trees.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/poll-types.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/primitives.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/spec.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/state-leaf.md
  website/versioned_docs/version-v2.0_alpha/developers-references/zk-snark-circuits/circuits.md
Labels: documentation

#1488 docs: separate deployment docs and keep up to date
  website/versioned_docs/version-v2.0_alpha/developers-references/integrating.md
  website/versioned_docs/version-v2.0_alpha/quick-start/deployment.md
  website/versioned_docs/version-v2.0_alpha/quick-start/poll-finalization.md
  website/versioned_docs/version-v2.0_alpha/quick-start/troubleshooting.md
Labels: documentation

#1489 chore(cleanup): remove references to topup
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/qv/processMessages.circom
  contracts/contracts/Poll.sol
  contracts/tasks/helpers/types.ts
Labels: chore

#1507 feat: coordinator public key method
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/app.module.ts
  coordinator/ts/auth/AccountSignatureGuard.service.ts
  coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
  coordinator/ts/common/errors.ts
  coordinator/ts/crypto/__tests__/crypto.service.test.ts
  coordinator/ts/crypto/crypto.module.ts
  coordinator/ts/crypto/crypto.service.ts
  coordinator/ts/file/__tests__/file.service.test.ts
  coordinator/ts/file/file.module.ts
  coordinator/ts/file/file.service.ts
  coordinator/ts/file/types.ts
  coordinator/ts/proof/__tests__/proof.service.test.ts
  coordinator/ts/proof/proof.service.ts
Labels: enhancement

#1506 test: fuzz testing for circuits
  circuits/circom/utils/calculateTotal.circom
  circuits/circom/utils/privToPubKey.circom
  circuits/package.json
  circuits/ts/__tests__/CalculateTotal.test.ts
  circuits/ts/__tests__/Hasher.test.ts
  circuits/ts/__tests__/PrivToPubKey.test.ts
  circuits/ts/__tests__/utils/constants.ts
  pnpm-lock.yaml
Labels: testing

#1512 feat(coordinator): update authorization
  .github/scripts/build.sh
  .github/workflows/coordinator-deploy.yml
  circuits/ts/__tests__/Hasher.test.ts
  circuits/ts/__tests__/PrivToPubKey.test.ts
  coordinator/.env.example
  coordinator/README.md
  coordinator/tests/app.test.ts
  coordinator/ts/auth/AccountSignatureGuard.service.ts
  coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
  coordinator/ts/file/__tests__/file.service.test.ts
  coordinator/ts/main.ts
Labels: documentation

#1476 docs(blog): add whats next for maci post
  website/blog/2024-05-28-upcoming-grants.md
Labels: documentation
