Repository privacy-ethereum/maci, pull requests merged in 2024-03, with the labels that each got.

#1260 feat(cli): return additional data from publish batch command
  cli/tests/unit/publish.test.ts
  cli/ts/commands/publish.ts
  cli/ts/utils/interfaces.ts
Labels: enhancement

#1278 docs(poll types): add docs describing type of polls (qv/non qv)
  website/versioned_docs/version-v1.x/poll-types.md
Labels: documentation

#1285 chore: update zk-kit compatible packages
  crypto/package.json
  pnpm-lock.yaml
Labels: dependencies

#1293 chore(contracts): support op sepolia deployment
  contracts/.env.example
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/tasks/helpers/constants.ts
Labels: chore

#1295 fix(core): add typescript dev dependency to fix build
  core/package.json
  pnpm-lock.yaml
Labels: bug

#1299 feat(cli): add initial voice credits from signup event
  cli/ts/commands/signup.ts
Labels: enhancement

#1310 chore(contracts): add acc queue contract to deployed contracts
  contracts/tasks/deploy/maci/10-maci.ts
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/ContractVerifier.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/verifyFull.ts
Labels: chore

#1302 fix(docs): fix inaccurate cli instructions
  website/versioned_docs/version-v1.x/cli.md
Labels: documentation

#1318 fix(contracts): use for-loop instead of async promise
  contracts/tests/MACI.test.ts
Labels: bug, chore

#1320 feat(cli): add provider fallback for poll data sdk method
  cli/tests/unit/poll.test.ts
  cli/ts/commands/poll.ts
  cli/ts/utils/interfaces.ts
Labels: enhancement

#1327 fix(build): add missing typescript dependency for integration tests package
  integrationTests/package.json
  pnpm-lock.yaml
Labels: bug
