Repository privacy-ethereum/maci, pull requests merged in 2024-08, with the labels that each got.

#1718 chore(coordinator): remove coordinator service package as it lives in a new repo
  .github/scripts/build.sh
  .github/scripts/deploy.sh
  .github/workflows/coordinator-build.yml
  .github/workflows/coordinator-deploy.yml
  coordinator/.env.example
  coordinator/.eslintrc.js
  coordinator/.gitignore
  coordinator/README.md
  coordinator/apps/Dockerfile
  coordinator/hardhat.config.js
  coordinator/nest-cli.json
  coordinator/package.json
  coordinator/scripts/generateKeypair.ts
  coordinator/tests/app.test.ts
  coordinator/ts/app.module.ts
  coordinator/ts/auth/AccountSignatureGuard.service.ts
  coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
  coordinator/ts/common/errors.ts
  coordinator/ts/common/index.ts
  coordinator/ts/common/networks.ts
  coordinator/ts/crypto/__tests__/crypto.service.test.ts
  coordinator/ts/crypto/crypto.module.ts
  coordinator/ts/crypto/crypto.service.ts
  coordinator/ts/file/__tests__/file.service.test.ts
  coordinator/ts/file/file.module.ts
  coordinator/ts/file/file.service.ts
  coordinator/ts/file/types.ts
  coordinator/ts/jest/setup.ts
  coordinator/ts/jest/transform.js
  coordinator/ts/main.ts
  coordinator/ts/proof/__tests__/proof.controller.test.ts
  coordinator/ts/proof/__tests__/proof.gateway.test.ts
  coordinator/ts/proof/__tests__/proof.service.test.ts
  coordinator/ts/proof/dto.ts
  coordinator/ts/proof/proof.controller.ts
  coordinator/ts/proof/proof.gateway.ts
  coordinator/ts/proof/proof.module.ts
  coordinator/ts/proof/proof.service.ts
  coordinator/ts/proof/types.ts
  coordinator/ts/subgraph/__tests__/subgraph.controller.test.ts
  coordinator/ts/subgraph/__tests__/subgraph.gateway.test.ts
  coordinator/ts/subgraph/__tests__/subgraph.service.test.ts
  coordinator/ts/subgraph/dto.ts
  coordinator/ts/subgraph/subgraph.controller.ts
  coordinator/ts/subgraph/subgraph.gateway.ts
  coordinator/ts/subgraph/subgraph.module.ts
  coordinator/ts/subgraph/subgraph.service.ts
  coordinator/ts/subgraph/types.ts
  coordinator/tsconfig.build.json
  coordinator/tsconfig.json
  lerna.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#1721 test(contracts): cleanup contracts tests
  contracts/tests/EASGatekeeper.test.ts
  contracts/tests/GitcoinPassportGatekeeper.test.ts
  contracts/tests/MACI.test.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Poll.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/TallyNonQv.test.ts
  contracts/tests/Verifier.test.ts
  contracts/tests/VkRegistry.test.ts
  contracts/tests/ZupassGatekeeper.test.ts
Labels: testing

#1700 chore: optimize message processor and tally
  .eslintrc.js
  .github/workflows/reusable-e2e.yml
  circuits/.gitignore
  circuits/circom/circuits.json
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/non-qv/tallyVotes.circom
  circuits/circom/core/qv/processMessages.circom
  circuits/circom/core/qv/tallyVotes.circom
  circuits/circom/test/ProcessMessages_10-2-1-2_test.circom
  circuits/circom/test/TallyVotes_10-1-2_test.circom
  circuits/circom/utils/hashers.circom
  circuits/circom/utils/processMessagesInputHasher.circom
  circuits/circom/utils/tallyVotesInputHasher.circom
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/Hasher.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  circuits/ts/__tests__/TallyVotes.test.ts
  circuits/ts/proofs.ts
  circuits/ts/types.ts
  cli/package.json
  cli/ts/commands/proveOnChain.ts
  contracts/contracts/MessageProcessor.sol
  contracts/contracts/Tally.sol
  contracts/contracts/crypto/MockVerifier.sol
  contracts/contracts/crypto/Verifier.sol
  contracts/contracts/interfaces/IMessageProcessor.sol
  contracts/contracts/interfaces/IVerifier.sol
  contracts/contracts/trees/LazyIMT.sol
  contracts/package.json
  contracts/tasks/helpers/Prover.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/TallyNonQv.test.ts
  contracts/tests/Verifier.test.ts
  core/ts/Poll.ts
  core/ts/__tests__/e2e.test.ts
  core/ts/__tests__/utils.test.ts
  core/ts/index.ts
  core/ts/utils/types.ts
  core/ts/utils/utils.ts
  integrationTests/package.json
  integrationTests/ts/__tests__/data/suites.json
  pnpm-lock.yaml
Labels: enhancement

#1725 chore: remove max values
  .github/scripts/downloadZkeys.ts
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  circuits/ts/__tests__/TallyVotes.test.ts
  circuits/ts/__tests__/utils/constants.ts
  cli/ts/commands/publish.ts
  contracts/contracts/MACI.sol
  contracts/contracts/Poll.sol
  contracts/contracts/PollFactory.sol
  contracts/contracts/interfaces/IPoll.sol
  contracts/contracts/interfaces/IPollFactory.sol
  contracts/contracts/utilities/Params.sol
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tests/MACI.test.ts
  contracts/tests/MessageProcessor.test.ts
  contracts/tests/Poll.test.ts
  contracts/tests/PollFactory.test.ts
  contracts/tests/Tally.test.ts
  contracts/tests/TallyNonQv.test.ts
  contracts/tests/constants.ts
  contracts/ts/genMaciState.ts
  core/ts/MaciState.ts
  core/ts/Poll.ts
  core/ts/__benchmarks__/index.ts
  core/ts/__benchmarks__/utils/constants.ts
  core/ts/__tests__/MaciState.test.ts
  core/ts/__tests__/Poll.test.ts
  core/ts/__tests__/e2e.test.ts
  core/ts/__tests__/utils/constants.ts
  core/ts/__tests__/utils/utils.ts
  core/ts/index.ts
  core/ts/utils/types.ts
  integrationTests/ts/__tests__/integration.test.ts
  subgraph/src/maci.ts
  subgraph/src/utils/constants.ts
  subgraph/tests/common.ts
  website/versioned_docs/version-v2.0_alpha/core-concepts/key-change.md
  website/versioned_docs/version-v2.0_alpha/core-concepts/spec.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Params.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Poll.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/PollFactory.md
Labels: chore

#1726 fix: add coordinator public key hash public input
  circuits/circom/circuits.json
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/qv/processMessages.circom
  circuits/circom/test/ProcessMessages_10-2-1-2_test.circom
  circuits/ts/__tests__/CeremonyParams.test.ts
  circuits/ts/__tests__/ProcessMessages.test.ts
  circuits/ts/types.ts
  cli/ts/commands/proveOnChain.ts
  contracts/contracts/MessageProcessor.sol
  contracts/tasks/helpers/Prover.ts
  contracts/ts/genMaciState.ts
  core/ts/Poll.ts
  core/ts/utils/types.ts
  website/versioned_docs/version-v2.0_alpha/core-concepts/spec.md
  website/versioned_docs/version-v2.0_alpha/developers-references/zk-snark-circuits/processMessages.md
  website/versioned_docs/version-v2.0_alpha/developers-references/zk-snark-circuits/tallyVotes.md
  website/versioned_docs/version-v2.0_alpha/quick-start/installation.md
Labels: bug

#1735 chore: use async fs instead of sync version
  .github/scripts/downloadZkeys.ts
  circuits/ts/compile.ts
  circuits/ts/genZkeys.ts
  circuits/ts/proofs.ts
  cli/tests/ceremony-params/ceremonyParams.test.ts
  cli/tests/constants.ts
  cli/tests/e2e/e2e.nonQv.test.ts
  cli/tests/e2e/e2e.test.ts
  cli/tests/e2e/keyChange.test.ts
  cli/tests/unit/poll.test.ts
  cli/tests/utils.ts
  cli/ts/commands/checkVerifyingKeys.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/deployVkRegistry.ts
  cli/ts/commands/genLocalState.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/mergeMessages.ts
  cli/ts/commands/mergeSignups.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/index.ts
  cli/ts/utils/storage.ts
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/runner/prove.ts
  integrationTests/ts/__tests__/integration.test.ts
Labels: chore

#1742 fix(circuits): use dynamic imports for promisify
  packages/circuits/ts/compile.ts
  packages/circuits/ts/proofs.ts
Labels: bug

#1749 chore(circuits): add constraint info print script
  packages/circuits/package.json
  packages/circuits/ts/info.ts
  pnpm-lock.yaml
Labels: chore

#1743 chore(release): publish 2.1.0
  CHANGELOG.md
  apps/subgraph/CHANGELOG.md
  apps/subgraph/package.json
  apps/website/CHANGELOG.md
  apps/website/package.json
  lerna.json
  package.json
  packages/circuits/CHANGELOG.md
  packages/circuits/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/contracts/CHANGELOG.md
  packages/contracts/package.json
  packages/integrationTests/CHANGELOG.md
  packages/integrationTests/package.json
  pnpm-lock.yaml
Labels: chore

#1770 feat(contracts): add virtual modifiers
  packages/contracts/contracts/Poll.sol
  packages/contracts/contracts/Tally.sol
  packages/contracts/contracts/extensions/interfaces/ISimpleProjectRegistry.sol
  packages/contracts/contracts/extensions/registry/SimpleRecipientRegistry.sol
  packages/contracts/tests/extensions/SimpleProjectRegistry.test.ts
Labels: enhancement

#1774 refactor(contracts): use custom factories for maci test deploys
  packages/contracts/tests/EASGatekeeper.test.ts
  packages/contracts/tests/GitcoinPassportGatekeeper.test.ts
  packages/contracts/tests/HatsGatekeeper.test.ts
  packages/contracts/tests/MACI.test.ts
  packages/contracts/tests/MessageProcessor.test.ts
  packages/contracts/tests/Poll.test.ts
  packages/contracts/tests/SemaphoreGatekeeper.test.ts
  packages/contracts/tests/SignUpGatekeeper.test.ts
  packages/contracts/tests/Tally.test.ts
  packages/contracts/tests/TallyNonQv.test.ts
  packages/contracts/tests/ZupassGatekeeper.test.ts
  packages/contracts/tests/utils.ts
  packages/contracts/ts/deploy.ts
  packages/contracts/ts/index.ts
  packages/contracts/ts/types.ts
Labels: chore

#1783 chore(release): publish 2.2.0
  CHANGELOG.md
  apps/subgraph/CHANGELOG.md
  apps/subgraph/package.json
  apps/website/CHANGELOG.md
  apps/website/package.json
  lerna.json
  package.json
  packages/circuits/CHANGELOG.md
  packages/circuits/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/contracts/CHANGELOG.md
  packages/contracts/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/crypto/CHANGELOG.md
  packages/crypto/package.json
  packages/domainobjs/CHANGELOG.md
  packages/domainobjs/package.json
  packages/integrationTests/CHANGELOG.md
  packages/integrationTests/package.json
  pnpm-lock.yaml
Labels: chore

#1785 chore(contracts): add deploy params type
  packages/contracts/ts/index.ts
Labels: chore

#1786 fix(contracts): remove poseidon builders from exports
  packages/contracts/ts/index.ts
Labels: bug

#1787 chore(contracts): move poseidon creation to compile script
  packages/contracts/scripts/compileSol.ts
  packages/contracts/ts/buildPoseidon.ts
Labels: chore

#1794 chore(contracts): extend ids for contract storage and deployment
  packages/contracts/tasks/helpers/ContractStorage.ts
  packages/contracts/tasks/helpers/Deployment.ts
  packages/contracts/tasks/helpers/types.ts
Labels: chore

#1796 feat(contracts): make poll modifiers virtual
  packages/contracts/contracts/Poll.sol
Labels: enhancement

#1797 chore(docs): remove version banner in v1.2
  apps/website/docusaurus.config.ts
  apps/website/versioned_docs/version-v1.2/introduction.md
Labels: documentation
