Repository privacy-ethereum/maci, pull requests merged in 2024-07, with the labels that each got.

#1626 refactor: optimize poll and tally contracts variables
  contracts/contracts/Poll.sol
  contracts/contracts/Tally.sol
Labels: chore

#1627 feat: proof parallelization
  contracts/contracts/MACI.sol
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/prove.ts
  coordinator/ts/proof/proof.service.ts
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
Labels: enhancement

#1637 chore(contracts): optimization and typo fixes
  contracts/contracts/Poll.sol
  contracts/contracts/interfaces/IMACI.sol
  contracts/contracts/interfaces/IPoll.sol
  website/versioned_docs/version-v1.2/solidity-docs/Poll.md
  website/versioned_docs/version-v1.2/solidity-docs/interfaces/IPoll.md
Labels: chore

#1638 feat(coordinator): add websockets support
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/helpers/types.ts
  contracts/ts/index.ts
  coordinator/README.md
  coordinator/package.json
  coordinator/tests/app.test.ts
  coordinator/ts/app.controller.ts
  coordinator/ts/app.module.ts
  coordinator/ts/auth/AccountSignatureGuard.service.ts
  coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
  coordinator/ts/events/__tests__/events.gateway.test.ts
  coordinator/ts/events/events.gateway.ts
  coordinator/ts/events/events.module.ts
  coordinator/ts/events/types.ts
  coordinator/ts/proof/proof.service.ts
  pnpm-lock.yaml
Labels: enhancement

#1645 chore(deployment): add missing text
  contracts/tasks/helpers/Deployment.ts
Labels: chore

#1646 docs: add links to the smart contracts code in the docs
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/AccQueue.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Gatekeepers.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MessageProcessor.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Params.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Poll.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/PollFactory.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Tally.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/VkRegistry.md
  website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/VoiceCreditProxy.md
Labels: documentation

#1643 feat(coordinator): deploy subgraph from coordinator service
  .github/workflows/coordinator-build.yml
  .gitignore
  circuits/circom/utils/processMessagesInputHasher.circom
  coordinator/.env.example
  coordinator/README.md
  coordinator/package.json
  coordinator/tests/app.test.ts
  coordinator/ts/app.module.ts
  coordinator/ts/common/errors.ts
  coordinator/ts/common/index.ts
  coordinator/ts/common/networks.ts
  coordinator/ts/proof/__tests__/proof.controller.test.ts
  coordinator/ts/proof/proof.controller.ts
  coordinator/ts/proof/proof.module.ts
  coordinator/ts/subgraph/__tests__/subgraph.controller.test.ts
  coordinator/ts/subgraph/__tests__/subgraph.service.test.ts
  coordinator/ts/subgraph/dto.ts
  coordinator/ts/subgraph/subgraph.controller.ts
  coordinator/ts/subgraph/subgraph.module.ts
  coordinator/ts/subgraph/subgraph.service.ts
  coordinator/ts/subgraph/types.ts
  pnpm-lock.yaml
  subgraph/.gitignore
  subgraph/config/network.json
  subgraph/config/scroll-sepolia.json
  subgraph/package.json
  website/static/img/offlineProcessing.svg
Labels: enhancement

#1652 chore: update pnpm to v9
  .github/workflows/benchmarks.yml
  .github/workflows/checks.yml
  .github/workflows/circuit-build.yml
  .github/workflows/commitlint.yml
  .github/workflows/contracts-build.yml
  .github/workflows/coordinator-build.yml
  .github/workflows/core-build.yml
  .github/workflows/crypto-build.yml
  .github/workflows/domainobjs-build.yml
  .github/workflows/e2e.yml
  .github/workflows/nightly-ceremony.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-e2e.yml
  .github/workflows/slither.yml
  .github/workflows/subgraph-build.yml
  coordinator/apps/Dockerfile
  package.json
  pnpm-lock.yaml
Labels: chore

#1644 refactor(circuits): remove duplicate constraints
  circuits/circom/core/non-qv/processMessages.circom
  circuits/circom/core/qv/processMessages.circom
  circuits/circom/utils/non-qv/messageValidator.circom
  circuits/circom/utils/non-qv/stateLeafAndBallotTransformer.circom
  circuits/circom/utils/qv/messageValidator.circom
  circuits/circom/utils/qv/stateLeafAndBallotTransformer.circom
  circuits/ts/__tests__/MessageValidator.test.ts
  circuits/ts/__tests__/StateLeafAndBallotTransformer.test.ts
Labels: circuits

#1653 fix: pnpm publish
  .npmrc
Labels: bug

#1651 feat(coordinator): deploy subgraph with websockets
  coordinator/tests/app.test.ts
  coordinator/ts/app.module.ts
  coordinator/ts/events/events.module.ts
  coordinator/ts/events/types.ts
  coordinator/ts/proof/__tests__/proof.gateway.test.ts
  coordinator/ts/proof/proof.gateway.ts
  coordinator/ts/proof/proof.module.ts
  coordinator/ts/proof/types.ts
  coordinator/ts/subgraph/__tests__/subgraph.gateway.test.ts
  coordinator/ts/subgraph/subgraph.gateway.ts
  coordinator/ts/subgraph/subgraph.module.ts
  coordinator/ts/subgraph/subgraph.service.ts
  coordinator/ts/subgraph/types.ts
Labels: enhancement

#1682 chore(circuits): optimize message to command
  circuits/circom/trees/incrementalQuinaryTree.circom
  circuits/circom/utils/messageToCommand.circom
  circuits/circom/utils/verifySignature.circom
Labels: chore
