Repository privacy-ethereum/maci, pull requests merged in 2024-12, with the labels that each got.

#1958 chore: use ubuntu-24.04 for ci jobs
  .github/workflows/benchmarks.yml
  .github/workflows/checks.yml
  .github/workflows/circuit-build.yml
  .github/workflows/codeql.yml
  .github/workflows/commitlint.yml
  .github/workflows/contracts-build.yml
  .github/workflows/core-build.yml
  .github/workflows/crypto-build.yml
  .github/workflows/domainobjs-build.yml
  .github/workflows/e2e.yml
  .github/workflows/hardhat-tasks.yml
  .github/workflows/nightly-ceremony.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/reusable-e2e.yml
  .github/workflows/slither.yml
  .github/workflows/subgraph-build.yml
  .github/workflows/typos.yml
Labels: devops, ci-bug, chore

#1960 chore: use view modifier for verifying poll proof
  packages/contracts/contracts/Poll.sol
Labels: chore

#1965 fix(contracts): use correct param for poll contract verification
  packages/contracts/tasks/deploy/poll/01-poll.ts
Labels: bug

#1970 feat(contracts): add ipfs service and prepare parsing ipfs data
  packages/contracts/.env.example
  packages/contracts/contracts/Poll.sol
  packages/contracts/package.json
  packages/contracts/tests/ipfs.test.ts
  packages/contracts/ts/genMaciState.ts
  packages/contracts/ts/ipfs.ts
  packages/contracts/ts/types.ts
  pnpm-lock.yaml
Labels: enhancement

#1969 docs(use-cases): updated use cases and case studies
  apps/website/versioned_docs/version-v2.x/case-studies.md
  apps/website/versioned_docs/version-v2.x/resources.md
  apps/website/versioned_docs/version-v2.x/use-cases/governance.md
  apps/website/versioned_docs/version-v2.x/use-cases/local-elections.md
  apps/website/versioned_docs/version-v2.x/use-cases/polling.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/_category_.json
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/public-goods.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/_category_.json
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/apply.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/faq.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/how-it-works.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/registration-approaches.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/what-is-quadratic-funding.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/retroactive-public-goods-funding/_category_.json
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/retroactive-public-goods-funding/case-studies.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/retroactive-public-goods-funding/how-it-works.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/retroactive-public-goods-funding/registration-approaches.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/retroactive-public-goods-funding/what-is-retroactive-public-goods-funding.md
  apps/website/versioned_docs/version-v2.x/use-cases/public-goods.md
Labels: documentation

#1971 feat(subgraph): add chain hashes and ipfs messages to subgraph
  apps/subgraph/schemas/schema.v1.graphql
  apps/subgraph/src/maci.ts
  apps/subgraph/src/poll.ts
  apps/subgraph/templates/subgraph.template.yaml
  apps/subgraph/tests/ipfs/batch-0.json
  apps/subgraph/tests/ipfs/batch-1.json
  apps/subgraph/tests/poll/poll.test.ts
  apps/subgraph/tests/poll/utils.ts
Labels: enhancement
