Repository privacy-ethereum/maci, pull requests merged in 2024-02, with the labels that each got.

#1177 docs(cli): update cli docs to reflect latest changes
  website/versioned_docs/version-v1.x/cli.md
Labels: documentation

#1172 chore(contracts): add proof generation for task coordinator
  circuits/ts/index.ts
  circuits/ts/types.ts
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/scripts/compileSol.sh
  contracts/tasks/deploy/maci/10-maci.ts
  contracts/tasks/deploy/maci/11-vkRegistry.ts
  contracts/tasks/deploy/poll/01-poll.ts
  contracts/tasks/helpers/ContractStorage.ts
  contracts/tasks/helpers/Deployment.ts
  contracts/tasks/helpers/ProofGenerator.ts
  contracts/tasks/helpers/Prover.ts
  contracts/tasks/helpers/TreeMerger.ts
  contracts/tasks/helpers/constants.ts
  contracts/tasks/helpers/types.ts
  contracts/tasks/runner/merge.ts
  contracts/tasks/runner/prove.ts
  contracts/testScriptLocalhost.sh
  contracts/ts/types.ts
  contracts/ts/utils.ts
Labels: chore

#1188 chore(cli): prepare cli package for web apps
  cli/package.json
  cli/tests/ceremony-params/ceremonyParams.test.ts
  cli/tests/constants.ts
  cli/tests/e2e/e2e.nonQv.test.ts
  cli/tests/e2e/e2e.subsidy.test.ts
  cli/tests/e2e/e2e.test.ts
  cli/tests/e2e/keyChange.test.ts
  cli/tests/unit/airdrop.test.ts
  cli/tests/unit/fundWallet.test.ts
  cli/tests/unit/timeTravel.test.ts
  cli/tests/unit/topup.test.ts
  cli/ts/commands/airdrop.ts
  cli/ts/commands/checkVerifyingKeys.ts
  cli/ts/commands/deploy.ts
  cli/ts/commands/deployPoll.ts
  cli/ts/commands/deployVkRegistry.ts
  cli/ts/commands/fundWallet.ts
  cli/ts/commands/genLocalState.ts
  cli/ts/commands/genProofs.ts
  cli/ts/commands/mergeMessages.ts
  cli/ts/commands/mergeSignups.ts
  cli/ts/commands/proveOnChain.ts
  cli/ts/commands/publish.ts
  cli/ts/commands/setVerifyingKeys.ts
  cli/ts/commands/signup.ts
  cli/ts/commands/timeTravel.ts
  cli/ts/commands/topup.ts
  cli/ts/commands/verify.ts
  cli/ts/index.ts
  cli/ts/sdk/index.ts
  cli/ts/utils/interfaces.ts
  integrationTests/ts/__tests__/integration.test.ts
Labels: chore

#1212 feat(cli): improve cli integration ux
  cli/testScript.sh
  cli/tests/e2e/e2e.test.ts
  cli/tests/e2e/keyChange.test.ts
  cli/ts/commands/index.ts
  cli/ts/commands/signup.ts
  cli/ts/index.ts
  cli/ts/sdk/index.ts
  cli/ts/utils/index.ts
  cli/ts/utils/interfaces.ts
  contracts/contracts/MACI.sol
  contracts/deploy-config-example.json
  contracts/ts/genMaciState.ts
  integrationTests/ts/__tests__/integration.test.ts
  website/versioned_docs/version-v1.x/cli.md
Labels: enhancement

#1222 fix(cli): run all the tests for package
  cli/tests/e2e/e2e.test.ts
Labels: bug

#1224 feat(cli): add get poll cli command
  cli/testScript.sh
  cli/tests/unit/poll.test.ts
  cli/ts/commands/index.ts
  cli/ts/commands/poll.ts
  cli/ts/commands/signup.ts
  cli/ts/index.ts
  cli/ts/sdk/index.ts
  cli/ts/utils/index.ts
  cli/ts/utils/interfaces.ts
  contracts/contracts/MACI.sol
  contracts/ts/genMaciState.ts
Labels: enhancement

#1251 feat(cli): add publish batch method for cli sdk
  cli/tests/unit/publish.test.ts
  cli/ts/commands/index.ts
  cli/ts/commands/publish.ts
  cli/ts/index.ts
  cli/ts/sdk/index.ts
  cli/ts/utils/index.ts
  cli/ts/utils/interfaces.ts
Labels: enhancement

#1256 fix(cli): read state index from event args
  cli/ts/commands/signup.ts
Labels: bug

#1259 fix(cli): generate ecdh shared key only one time
  cli/ts/commands/publish.ts
Labels: bug
