Repository privacy-ethereum/maci, pull requests merged in 2025-02, with the labels that each got.

#2102 feat(sdk): add relayer functions
  apps/relayer/tests/messageBatches.test.ts
  apps/relayer/tests/messages.test.ts
  apps/relayer/ts/message/__tests__/message.controller.test.ts
  apps/relayer/ts/message/__tests__/message.repository.test.ts
  apps/relayer/ts/message/__tests__/message.service.test.ts
  apps/relayer/ts/message/__tests__/utils.ts
  apps/relayer/ts/message/__tests__/validation.test.ts
  apps/relayer/ts/message/message.dto.ts
  apps/relayer/ts/message/message.repository.ts
  apps/relayer/ts/message/message.schema.ts
  apps/relayer/ts/message/message.service.ts
  apps/relayer/ts/message/types.ts
  apps/relayer/ts/message/validation.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.repository.test.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
  apps/relayer/ts/messageBatch/__tests__/utils.ts
  apps/relayer/ts/messageBatch/messageBatch.controller.ts
  apps/relayer/ts/messageBatch/messageBatch.dto.ts
  apps/relayer/ts/messageBatch/messageBatch.repository.ts
  apps/relayer/ts/messageBatch/messageBatch.service.ts
  apps/subgraph/schemas/schema.v1.graphql
  apps/subgraph/src/poll.ts
  apps/subgraph/tests/common.ts
  apps/subgraph/tests/ipfs/batch-0.json
  apps/subgraph/tests/ipfs/batch-1.json
  apps/subgraph/tests/poll/utils.ts
  packages/contracts/ts/genMaciState.ts
  packages/contracts/ts/index.ts
  packages/contracts/ts/types.ts
  packages/sdk/jest.config.json
  packages/sdk/package.json
  packages/sdk/ts/poll/poll.ts
  packages/sdk/ts/poll/types.ts
  packages/sdk/ts/poll/utils.ts
  packages/sdk/ts/relayer/__tests__/messages.test.ts
  packages/sdk/ts/relayer/__tests__/utils.test.ts
  packages/sdk/ts/relayer/index.ts
  packages/sdk/ts/relayer/messages.ts
  packages/sdk/ts/relayer/types.ts
  packages/sdk/ts/relayer/utils.ts
  pnpm-lock.yaml
Labels: enhancement

#2114 feat(relayer): add deploy scripts
  .dockerignore
  apps/relayer/Dockerfile
  apps/relayer/docker-compose.yml
  apps/relayer/package.json
  apps/relayer/tests/app.test.ts
  apps/relayer/tests/constants.ts
  apps/relayer/tests/deploy.ts
  apps/relayer/tests/messageBatches.test.ts
  apps/relayer/tests/messages.test.ts
  apps/relayer/ts/app.module.ts
  apps/relayer/ts/health/__tests__/health.controller.test.ts
  apps/relayer/ts/health/health.controller.ts
  apps/relayer/ts/health/health.module.ts
  apps/relayer/ts/ipfs/__tests__/ipfs.service.test.ts
  apps/relayer/ts/ipfs/ipfs.module.ts
  apps/relayer/ts/jest/setup.ts
  apps/relayer/ts/main.ts
  apps/relayer/ts/message/__tests__/message.controller.test.ts
  apps/relayer/ts/message/__tests__/message.guard.test.ts
  apps/relayer/ts/message/__tests__/message.repository.test.ts
  apps/relayer/ts/message/__tests__/message.service.test.ts
  apps/relayer/ts/message/__tests__/utils.ts
  apps/relayer/ts/message/__tests__/validation.test.ts
  apps/relayer/ts/message/message.controller.ts
  apps/relayer/ts/message/message.dto.ts
  apps/relayer/ts/message/message.guard.ts
  apps/relayer/ts/message/message.module.ts
  apps/relayer/ts/message/message.repository.ts
  apps/relayer/ts/message/message.schema.ts
  apps/relayer/ts/message/message.service.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.controller.test.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.repository.test.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
  apps/relayer/ts/messageBatch/__tests__/utils.ts
  apps/relayer/ts/messageBatch/__tests__/validation.test.ts
  apps/relayer/ts/messageBatch/messageBatch.controller.ts
  apps/relayer/ts/messageBatch/messageBatch.dto.ts
  apps/relayer/ts/messageBatch/messageBatch.module.ts
  apps/relayer/ts/messageBatch/messageBatch.repository.ts
  apps/relayer/ts/messageBatch/messageBatch.schema.ts
  apps/relayer/ts/messageBatch/messageBatch.service.ts
  apps/relayer/tsconfig.build.json
  apps/relayer/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, devops

#2132 test(relayer): add checks for onchain publishing
  apps/relayer/tests/deploy.ts
  apps/relayer/tests/onchain.test.ts
  apps/relayer/ts/ipfs/__tests__/ipfs.service.test.ts
  apps/relayer/ts/ipfs/ipfs.service.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
  apps/relayer/ts/messageBatch/messageBatch.service.ts
  packages/sdk/ts/index.ts
  packages/sdk/ts/poll/index.ts
Labels: testing

#2143 test(relayer): add more e2e tests
  .github/workflows/relayer-build.yml
  apps/relayer/.env.example
  apps/relayer/docker-compose.yml
  apps/relayer/tests/deploy.ts
  apps/relayer/ts/message/message.service.ts
  apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
  apps/relayer/ts/messageBatch/messageBatch.service.ts
  packages/cli/.gitignore
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/utils.ts
  packages/cli/ts/commands/genLocalState.ts
  packages/cli/ts/commands/genProofs.ts
  packages/cli/ts/commands/proveOnChain.ts
  packages/cli/ts/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/contracts/contracts/MessageProcessor.sol
  packages/contracts/tasks/helpers/ProofGenerator.ts
  packages/contracts/tasks/helpers/Prover.ts
  packages/contracts/tasks/helpers/types.ts
  packages/contracts/tasks/runner/prove.ts
  packages/contracts/tests/ipfs.test.ts
  packages/contracts/ts/genMaciState.ts
  packages/contracts/ts/ipfs.ts
  packages/contracts/ts/types.ts
  packages/core/ts/Poll.ts
  packages/integrationTests/.gitignore
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/integrationTests/ts/__tests__/utils/constants.ts
  packages/integrationTests/ts/__tests__/utils/utils.ts
  packages/sdk/package.json
  packages/sdk/ts/relayer/__tests__/utils.test.ts
  packages/sdk/ts/relayer/index.ts
  packages/sdk/ts/relayer/messages.ts
  packages/sdk/ts/relayer/types.ts
  packages/sdk/ts/relayer/utils.ts
  packages/sdk/ts/utils/cid.ts
  packages/sdk/ts/utils/index.ts
  pnpm-lock.yaml
Labels: testing

#2167 docs(relayer): add general documentation for service
  apps/relayer/README.md
  apps/relayer/relayer-diagram.png
Labels: documentation

#2179 refactor(cli): cleanup signup command
  apps/relayer/tests/deploy.ts
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/joinPoll.test.ts
  packages/cli/tests/unit/publish.test.ts
  packages/cli/tests/unit/signup.test.ts
  packages/cli/ts/commands/checkVerifyingKeys.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/sdk/ts/maci/gatekeeper.ts
  packages/sdk/ts/maci/index.ts
  packages/sdk/ts/maci/types.ts
Labels: chore

#2180 refactor(cli): move key generation commands to sdk
  packages/cli/tests/unit/genKeyPair.test.ts
  packages/cli/tests/unit/genPubkey.test.ts
  packages/cli/ts/commands/genKeyPair.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/poll.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/sdk/ts/keys/__tests__/keypair.test.ts
  packages/sdk/ts/keys/__tests__/publicKeys.test.ts
  packages/sdk/ts/keys/index.ts
  packages/sdk/ts/keys/keypair.ts
  packages/sdk/ts/keys/publicKeys.ts
  packages/sdk/ts/keys/types.ts
Labels: chore

#2181 refactor(cli): move signups merging to sdk
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/poll.test.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/mergeSignups.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/sdk/ts/index.ts
  packages/sdk/ts/maci/index.ts
  packages/sdk/ts/maci/merge.ts
  packages/sdk/ts/maci/types.ts
  packages/sdk/ts/poll/utils.ts
Labels: chore

#2183 refactor(cli): use verify from sdk
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/verify.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
Labels: chore

#2184 refactor(cli): move vk commands to sdk
  apps/relayer/tests/deploy.ts
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/joinPoll.test.ts
  packages/cli/tests/unit/poll.test.ts
  packages/cli/tests/unit/publish.test.ts
  packages/cli/tests/unit/signup.test.ts
  packages/cli/ts/commands/checkVerifyingKeys.ts
  packages/cli/ts/commands/extractVkToFile.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/setVerifyingKeys.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/sdk/ts/keys/checkVerifyingKeys.ts
  packages/sdk/ts/keys/index.ts
  packages/sdk/ts/keys/setVerifyingKeys.ts
  packages/sdk/ts/keys/types.ts
  packages/sdk/ts/keys/utils.ts
  packages/sdk/ts/keys/verifyingKeys.ts
Labels: chore

#2185 refactor(cli): move maci state generation to sdk
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/ts/commands/deployPoll.ts
  packages/cli/ts/commands/genProofs.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/joinPoll.ts
  packages/cli/ts/commands/proveOnChain.ts
  packages/cli/ts/commands/publish.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/contracts.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/integrationTests/ts/__tests__/utils/utils.ts
  packages/sdk/ts/maci/index.ts
  packages/sdk/ts/maci/state.ts
  packages/sdk/ts/maci/types.ts
Labels: chore

#2187 refactor(cli): move prove onchain to sdk
  .gitignore
  apps/relayer/tests/deploy.ts
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/joinPoll.test.ts
  packages/cli/ts/commands/genProofs.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/joinPoll.ts
  packages/cli/ts/commands/proveOnChain.ts
  packages/cli/ts/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/cli/ts/utils/verifiers.ts
  packages/contracts/tasks/runner/submitOnChain.ts
  packages/contracts/ts/index.ts
  packages/contracts/ts/proofs.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/integrationTests/ts/__tests__/utils/utils.ts
  packages/sdk/ts/index.ts
  packages/sdk/ts/proof/generate.ts
  packages/sdk/ts/proof/index.ts
  packages/sdk/ts/proof/prove.ts
  packages/sdk/ts/proof/types.ts
  packages/sdk/ts/proofs/index.ts
  packages/sdk/ts/trees/stateTree.ts
  packages/sdk/ts/user/types.ts
  packages/sdk/ts/user/user.ts
  packages/sdk/ts/user/utils.ts
  packages/sdk/ts/utils/index.ts
  packages/sdk/ts/utils/params.ts
Labels: chore

#2188 refactor(cli): move publish commands to sdk
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/publish.test.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/publish.ts
  packages/cli/ts/index.ts
  packages/cli/ts/sdk/index.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/sdk/ts/vote/index.ts
  packages/sdk/ts/vote/publish.ts
  packages/sdk/ts/vote/types.ts
Labels: chore

#2193 Return processProofs, tallyProofs and tallyData in generateProofs function
  packages/cli/ts/commands/genProofs.ts
  packages/sdk/ts/proof/generate.ts
  packages/sdk/ts/proof/index.ts
  packages/sdk/ts/proof/types.ts
Labels: bug

#2191 refactor(cli): move proof generation and poll deploy to sdk
  apps/relayer/tests/deploy.ts
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/joinPoll.test.ts
  packages/cli/tests/unit/poll.test.ts
  packages/cli/tests/unit/publish.test.ts
  packages/cli/tests/unit/utils.test.ts
  packages/cli/ts/commands/genProofs.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/index.ts
  packages/cli/ts/utils/formatting.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/cli/ts/utils/salt.ts
  packages/cli/ts/utils/verifiers.ts
  packages/cli/ts/utils/vks.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/integrationTests/ts/__tests__/utils/constants.ts
  packages/sdk/ts/deploy/poll.ts
  packages/sdk/ts/deploy/types.ts
  packages/sdk/ts/keys/utils.ts
  packages/sdk/ts/proof/generate.ts
  packages/sdk/ts/proof/types.ts
  packages/sdk/ts/utils/index.ts
  packages/sdk/ts/utils/params.ts
  packages/sdk/ts/vote/index.ts
Labels: chore

#2192 refactor(cli): move deploy vk registry and testing commands to sdk
  apps/relayer/hardhat.config.cjs
  apps/relayer/tests/deploy.ts
  packages/cli/tests/ceremony-params/ceremonyParams.test.ts
  packages/cli/tests/constants.ts
  packages/cli/tests/e2e/e2e.nonQv.test.ts
  packages/cli/tests/e2e/e2e.test.ts
  packages/cli/tests/e2e/keyChange.test.ts
  packages/cli/tests/unit/joinPoll.test.ts
  packages/cli/tests/unit/poll.test.ts
  packages/cli/tests/unit/publish.test.ts
  packages/cli/tests/unit/signup.test.ts
  packages/cli/tests/unit/timeTravel.test.ts
  packages/cli/ts/commands/deploy.ts
  packages/cli/ts/commands/deployVkRegistry.ts
  packages/cli/ts/commands/fundWallet.ts
  packages/cli/ts/commands/index.ts
  packages/cli/ts/commands/showContracts.ts
  packages/cli/ts/commands/timeTravel.ts
  packages/cli/ts/index.ts
  packages/cli/ts/utils/constants.ts
  packages/cli/ts/utils/defaults.ts
  packages/cli/ts/utils/index.ts
  packages/cli/ts/utils/interfaces.ts
  packages/cli/ts/utils/storage.ts
  packages/contracts/ts/deploy.ts
  packages/integrationTests/ts/__tests__/integration.test.ts
  packages/sdk/ts/deploy/index.ts
  packages/sdk/ts/deploy/types.ts
  packages/sdk/ts/deploy/vkRegistry.ts
  packages/sdk/ts/user/user.ts
  packages/sdk/ts/utils/__tests__/fundWallet.test.ts
  packages/sdk/ts/utils/__tests__/timeTravel.test.ts
  packages/sdk/ts/utils/fundWallet.ts
  packages/sdk/ts/utils/index.ts
  packages/sdk/ts/utils/timeTravel.ts
  packages/sdk/ts/utils/types.ts
Labels: chore
